[theme]

# Primary accent for interactive elements
primaryColor = '#2ED158'

# Background color for the main content area
backgroundColor = '#000'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#2ED158'

# Color used for almost all text
textColor = '#FFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"